# Generated by Django 5.2.4 on 2025-10-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
    ]
