# Generated by Django 4.2.11 on 2026-03-16 18:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20251029_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('positive_percentage', models.FloatField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('neutral_percentage', models.FloatField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('negative_percentage', models.FloatField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('suggestion', models.TextField(blank=True)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
