# Generated by Django 4.2.11 on 2026-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_summary_lineuser_user_metadata'),
    ]

    operations = [
        # user_metadata อาจถูกสร้างไว้แล้วในฐานข้อมูล (manual / migration เก่า) — อย่า AddField ซ้ำ
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='lineuser',
                    name='user_metadata',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE chat_lineuser "
                        "ADD COLUMN IF NOT EXISTS user_metadata jsonb DEFAULT '{}'::jsonb;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='slip_public_url',
            field=models.TextField(blank=True, help_text='Public URL after upload to Supabase Storage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='slip_storage_path',
            field=models.CharField(blank=True, help_text='Object path in bucket e.g. payment/<id>.png', max_length=512),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Masked receiver account / PromptPay ref from slip', max_length=255),
        ),
    ]
