# Generated by Django 4.2.11 on 2026-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_payment_single_url_remove_verification'),
    ]

    operations = [

        migrations.AddField(
            model_name='summary',
            name='ratings_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, help_text='URL สาธารณะของสลิป (Supabase หรือ /media/payment/… ถ้าใช้ fallback)'),
        ),
    ]
