# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_trip_created_by_summary_ratings_stats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="highlights",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="จุดเด่นเชิงบวกจากรีวิว (title/description/mentions) สำหรับแดชบอร์ด",
            ),
        ),
        migrations.AddField(
            model_name="summary",
            name="suggestion_bullets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="รายการคำแนะนำแบบ structured (สตริงต่อข้อ) แยกจาก suggestion เดิม",
            ),
        ),
    ]
