"""
Django settings for tripbot project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import os

load_dotenv()

# Frontend Setting
FRONTEND_URL = os.getenv('FRONTEND_URL')
# Line Messaging API settings
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET')
LINE_CHANNEL_NGROK_BASE = os.getenv("LINE_CHANNEL_NGROK_BASE", "")

# SlipOK — ตรวจสลิป (https://slipok.com)
# ส่ง API จริงแค่: SLIPOK_API_KEY (header x-authorization) + SLIPOK_BRANCH_ID (path) + log/amount ใน slipok.py
# การเทียบผู้รับบนสลิปกับร้าน — ตั้งที่ SlipOK dashboard สาขานั้น (ไม่ได้อ่านจาก env ด้านล่าง)
# ค่า SLIPOK_BANK_* / SLIPOK_PROMPTPAY_* / SLIPOK_BANK_ACCOUNT_OWNER = ใช้แสดงข้อความชำระเงินใน LINE เท่านั้น
SLIPOK_API_KEY = (os.getenv("SLIPOK_API_KEY") or "").strip()
SLIPOK_BRANCH_ID = (os.getenv("SLIPOK_BRANCH_ID") or "").strip()
SLIPOK_LOG = os.getenv("SLIPOK_LOG", "true").lower() in ("1", "true", "yes")
SLIPOK_BANK_CODE = os.getenv("SLIPOK_BANK_CODE")
SLIPOK_BANK_NAME = os.getenv("SLIPOK_BANK_NAME")
SLIPOK_BANK_NAME_TH = os.getenv("SLIPOK_BANK_NAME_TH")
SLIPOK_BANK_ACCOUNT_NUMBER = os.getenv("SLIPOK_BANK_ACCOUNT_NUMBER")
SLIPOK_PROMPTPAY_NUMBER = os.getenv("SLIPOK_PROMPTPAY_NUMBER")
SLIPOK_BANK_ACCOUNT_OWNER = os.getenv("SLIPOK_BANK_ACCOUNT_OWNER")
PROMPTPAY_QR_IMAGE_URL = os.getenv(
    "PROMPTPAY_QR_IMAGE_URL",
    "https://fcnuamycwiqdgcrwlcba.supabase.co/storage/v1/object/public/app-object-storage/payment/promptpay.png",
)

# Supabase Storage — อัปโหลดสลิปหลัง SlipOK ผ่าน
SUPABASE_URL = (os.getenv("SUPABASE_URL") or "").rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPABASE_OBJECT_STORAGE = os.getenv("SUPABASE_OBJECT_STORAGE", "app-object-storage")
# ถ้าไม่มี Supabase key — fallback บันทึกไฟล์ใต้ MEDIA_ROOT และใช้ URL นี้ต่อท้าย /media/...
PUBLIC_BACKEND_URL = (os.getenv("PUBLIC_BACKEND_URL") or "").strip().rstrip("/")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_API_URL = os.getenv("OPENROUTER_API_URL", "https://openrouter.ai/api/v1")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

if not SECRET_KEY and not DEBUG:
    raise ImproperlyConfigured(
        "ตั้งค่า DJANGO_SECRET_KEY ใน Cloud Run → Variables (หรือ Secret Manager)"
    )
if not SECRET_KEY and DEBUG:
    SECRET_KEY = "django-insecure-dev-only-local"

#ALLOWED_HOSTS = [
#    "localhost",
#    "127.0.0.1",
#    "3ce00f03d31e.ngrok-free.app",  # <-- เพิ่มโดเมนของ ngrok ใช้อยู่
#]

ALLOWED_HOSTS = ['*']  # เปิดกว้างทุก host (เฉพาะตอนพัฒนาเท่านั้น!!)




# Application definition

# daphne ต้องอยู่ก่อน channels — แล้ว `python manage.py runserver` จะรัน ASGI รองรับ WebSocket
# (pip install daphne channels)
INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'corsheaders',
    'rest_framework',  # สำหรับ API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'tripbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tripbot.wsgi.application'
ASGI_APPLICATION = 'tripbot.asgi.application'

# Django Channels — WebSocket (React); use Redis in production for multi-worker
_redis_url = (os.getenv('REDIS_URL') or '').strip()
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# แจ้งเตือน booking ใหม่ (บันทึกลง DB + broadcast WS) — ปิดชั่วคราวเช่น ตอนรัน mock
BOOKING_NOTIFICATIONS_ENABLED = os.getenv('BOOKING_NOTIFICATIONS_ENABLED', 'true').lower() in (
    '1', 'true', 'yes',
)
# React เชื่อม ws://.../ws/admin/notifications/?token=...
ADMIN_WS_TOKEN = (os.getenv('ADMIN_WS_TOKEN') or '').strip()


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_host = (os.environ.get("DB_HOST") or "").strip()
# Supabase Postgres ทางอินเทอร์เน็ต — ใช้ SSL เสมอเมื่อมี HOST
_db_options = {"sslmode": "require"} if _db_host else {}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT") or "5432",
        "OPTIONS": _db_options,
    },
}

# Supabase pooler (PgBouncer transaction mode, พอร์ต 6543): ปิด server-side cursors — กัน OperationalError / 500 บน Cloud Run
_db_port = (os.environ.get("DB_PORT") or "").strip()
if "pooler.supabase.com" in _db_host or _db_port == "6543":
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True

# Cloud Run + Postgres ภายนอก: ไม่เก็บ connection ค้าง (ลด stale / pooler เต็ม)
if not DEBUG:
    DATABASES["default"]["CONN_MAX_AGE"] = 0

# Docker build: Dockerfile ตั้ง DJANGO_BUILD_PHASE=1 → not _is_image_build เป็น False → เงื่อนไขด้านล่างเป็น False ทั้งก้อน (ไม่ raise) แม้ไม่มี DB_*
_is_image_build = os.environ.get("DJANGO_BUILD_PHASE") == "1"
if not DEBUG and not _is_image_build and not (_db_host and os.environ.get("DB_NAME")):
    raise ImproperlyConfigured(
        "Production ใช้ Supabase Postgres เสมอ — ตั้งค่า DB_HOST, DB_NAME, DB_USER, DB_PASSWORD, DB_PORT "
        "ใน Cloud Run ให้ตรง Supabase Dashboard → Database"
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework — session cookie สำหรับแดชบอร์ด admin
# ใช้ SessionAuthenticationWithoutCSRF เพื่อไม่ให้ POST จาก SPA ข้ามโดเมนโดน 403 CSRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "chat.authentication.SessionAuthenticationWithoutCSRF",
    ],
}

# CORS — ต้องระบุ origin แบบชัดเจนเมื่อใช้ credentials (cookie session)
_cors_origins = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,https://tripbot-frontend-294086862024.asia-southeast1.run.app",
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True

# เก่า: CORS_ALLOW_ALL_ORIGINS = True — ปิดเมื่อใช้ credentials
CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Local: Lax + ไม่บังคับ Secure (http://)
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True

# Production (frontend คนละโดเมนกับ API เช่น Cloud Run): ต้อง SameSite=None + Secure
# ไม่งั้น fetch(..., credentials: "include") จาก https://tripbot-frontend-....run.app จะไม่ยอมแนบ session cookie
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"

# Cloud Logging / Daphne — ส่ง traceback ไป stdout
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}