"""
Django settings for tripbot project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

# Frontend Setting
FRONTEND_URL = os.getenv('FRONTEND_URL')
# Line Messaging API settings
LINE_CHANNEL_ACCESS_TOKEN = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.getenv('LINE_CHANNEL_SECRET')
LINE_CHANNEL_NGROK_BASE = os.getenv("LINE_CHANNEL_NGROK_BASE", "")

# SlipOK — ตรวจสลิปโอนเงิน (https://slipok.com)
# URL: POST https://api.slipok.com/api/line/apikey/<BRANCH_ID>  header x-authorization: <API_KEY>
SLIPOK_API_KEY = os.getenv("SLIPOK_API_KEY")
SLIPOK_BRANCH_ID = os.getenv("SLIPOK_BRANCH_ID") or os.getenv("SLIPOK_SECRET_KEY")
SLIPOK_LOG = os.getenv("SLIPOK_LOG", "true").lower() in ("1", "true", "yes")
SLIPOK_BANK_CODE = os.getenv("SLIPOK_BANK_CODE")
SLIPOK_BANK_NAME = os.getenv("SLIPOK_BANK_NAME")
SLIPOK_BANK_NAME_TH = os.getenv("SLIPOK_BANK_NAME_TH")
SLIPOK_BANK_ACCOUNT_NUMBER = os.getenv("SLIPOK_BANK_ACCOUNT_NUMBER")
# ข้อความแสดงลูกค้าตอนโอน PromptPay (LINE)
SLIPOK_PROMPTPAY_NUMBER = os.getenv("SLIPOK_PROMPTPAY_NUMBER")
SLIPOK_BANK_ACCOUNT_OWNER = os.getenv("SLIPOK_BANK_ACCOUNT_OWNER")
PROMPTPAY_QR_IMAGE_URL = os.getenv(
    "PROMPTPAY_QR_IMAGE_URL",
    "https://fcnuamycwiqdgcrwlcba.supabase.co/storage/v1/object/public/app-object-storage/payment/promptpay.png",
)

# Supabase Storage — อัปโหลดสลิปหลัง SlipOK ผ่าน
SUPABASE_URL = (os.getenv("SUPABASE_URL") or "").rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPABASE_OBJECT_STORAGE = os.getenv("SUPABASE_OBJECT_STORAGE", "app-object-storage")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_API_URL = os.getenv("OPENROUTER_API_URL", "https://openrouter.ai/api/v1")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

#ALLOWED_HOSTS = [
#    "localhost",
#    "127.0.0.1",
#    "3ce00f03d31e.ngrok-free.app",  # <-- เพิ่มโดเมนของ ngrok ใช้อยู่
#]

ALLOWED_HOSTS = ['*']  # เปิดกว้างทุก host (เฉพาะตอนพัฒนาเท่านั้น!!)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'corsheaders',
    'rest_framework',  # สำหรับ API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'tripbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tripbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    },
    
    "OPTIONS": {
            "sslmode": "require",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'th'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework — session cookie สำหรับแดชบอร์ด admin
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# CORS — ต้องระบุ origin แบบชัดเจนเมื่อใช้ credentials (cookie session)
_cors_origins = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173",
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True

# เก่า: CORS_ALLOW_ALL_ORIGINS = True — ปิดเมื่อใช้ credentials
CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True